replicaCount: 2

image:
  repository: gcr.io/{{ .Values.gcpProject }}/interview-fe
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

env:
  - name: NODE_ENV
    value: "production"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
